name: C++ Problem Generation and Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: pip install openai

    - name: Generate Problem
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python generate_problem.py

    - name: Commit and push changes
      env:
        ACTIONS_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add README.md src/solution.cpp tests/test_solution.cpp
        git commit -m "Add generated problem"
        # Pull the latest changes from the remote to avoid conflicts
        git pull --rebase origin main
        # Push the changes
        git push https://x-access-token:${ACTIONS_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
